import {
    CONTRACTS,
    DATA_AVAILABILITY,
    EXITS,
    FORCE_TRANSACTIONS,
    OPERATOR,
    STATE_CORRECTNESS,
} from './common'
import { Project } from './types'

export const idleFinance: Project = {
    name: 'Idle Finance',
    slug: 'idle-finance',
    bridges: [],
    associatedTokens: [],
    details: {
        description: 'Idle finance is a decentralized protocol that offers multiple products and in this way creating a one-stop source of yield in DeFi. The protocol allows its users to algorithmically optimize their digital asset allocation using multiple DeFi protocols. This can be adjusted on the risk appetite for a certain user as well.',
        benefits: 'Having stkIDLE offers a few opportunities for its holders compared to just having IDLE. ',
        voting: 'The IDLE token can be locked to obtain stkIDLE (this means locking your tokens up for a predetermined period of time). The stkIDLE won’t be transferable and the longer the token is staked, the more voting power a user will have. By locking these tokens up, a user will get voting rights in the governance of the DAO. This can be used to vote on proposals in which you agree (or not).',
        gaugeWeights: 'Idle finance offers the opportunity to direct the incentivization of different Perpetual Yield Trenches (PYT). These PYT’s are capital pools that automatically generate and tranche yields and risks based on a range of market-neutral yield strategies. The incentivization will be based on the gauge weight a certain PYT has. In the first phase this will only apply to the senior classes of the PYT.',
        rewards: 'Users who hold stkIDLE will have the right to receive certain amount of fees generated by the protocol. The holders of sktIDLE will also be able to boost their individual rewards.',
        purpose: 'Exchange',
        status: 'In progress',
        links: {
            websites: ['https://idle.finance/#/'],
            apps: [''],
            documentation: ['https://docs.idle.finance'],
            explorers: ['https://gov.idle.finance/t/introducing-idle-gauges-model-for-tranches/913/7'],
            governance: ['https://gov.idle.finance'],
            repositories: ['https://github.com/Idle-Labs/'],
            socialMedia: [
                'https://twitter.com/idlefinance',
                'https://discord.com/invite/mpySAJp',
            ],
        },
        technology: {
            category: {
                name: 'Yield',
                details: 'idle-finance',
            },
            contracts: {
                addresses: [
                    {
                        name: 'Idle Finance',
                        address: '0x875773784Af8135eA0ef43b5a374AaD105c5D39e',
                    }
                ],
            },
        },
    },
}
