import {Project} from './types'

export const stakeDAO: Project = {
    name: 'StakeDAO',
    slug: 'stakeDAO',
    bridges: [],
    associatedTokens: [],
    details: {
        description:
            'Stake DAO is a decentralized platform that enables its users to enforce growth strategies in DeFi with the convenience of a simple dashboard to deploy multiple possibilities to grow their crypto portfolio. The protocol therefore in return will get a cut of the profits generated by the deposited funds.',
        benefits: 'Having veSTD offers a few opportunities for its holders compared to just having STD.',
        voting: 'The STD can be time-locked for veSTD (this means locking up the token for a certain period of time). The veSTD is a non-transferable token. The longer the STD tokens are staked, up to 4 years, the more veSTD you’ll receive in return. Locking up these tokens grants you voting rights in the governance of the DAO. You can use these votes if you (dis)agree with certain proposals.',
        gaugeWeights: "Stake DAO offers the possibility to direct the incentivization of different lockers. The incentivization will be determined based on the gauge weight a locker has. The bigger the gauge weight, the more STD a locker will receive. Users who don’t have any active strategy are able to delegate their boost.",
        rewards: "Holders of veSTD will get up to a 2.5x boost of the STD rewards and in the meantime it will also generate points for the Stake DAO NFT’s. Stake DAO also collects 15% performance fee on all profit generated and has a 0.5% withdrawal fee across all different strategies. The fees are collected in the native currency of each strategy (i.e. USD, BTC and EUR) and are distributed to users that lock their SDT to participate in the governance.",
        purpose: 'Exchange',
        status: 'On',
        links: {
            websites: ['https://stakedao.org'],
            apps: [''],
            documentation: ['https://stakedao.gitbook.io/'],
            explorers: [''],
            governance: ['https://gov.stakedao.org/'],
            repositories: ['https://github.com/StakeDAO/'],
            socialMedia: [
                'https://twitter.com/StakeDAOHQ',
                'https://discord.com/invite/stakedaohq',
            ],
        },
        technology: {
            category: {
                name: 'Yield',
                details: 'stakeDAO',
            },
            contracts: {
                addresses: [
                    {
                        name: 'Stake DAO Token',
                        address: '0x73968b9a57c6e53d41345fd57a6e6ae27d6cdb2f',
                    },
                    {
                        name: 'Voting Escrow (veSDT Token)',
                        address: '0x0C30476f66034E11782938DF8e4384970B6c9e8a',
                    },
                    {
                        name: 'Fee Distributor',
                        address: '0x29f3dd38dB24d3935CF1bf841e6b2B461A3E5D92',
                    },
                ],
            },
        },
    },
}
